version: '2'
services:
    sandboxhipster-app:
        image: sandboxhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sandboxhipster-mysql:3306/sandboxhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sandboxhipster-mysql:
        extends:
            file: mysql.yml
            service: sandboxhipster-mysql
